### ISSUE TITLE
GAM.db building

### ISSUE THREAD

**Issue by gandrianov** [ctlab/GAM#1]
Hello! Could you say how look rpair and rptype in GAM.db/kegg/process_reaction.py?
I try to build this with using KEGG's REST API.

Thank you in advance!

**Comment by assaron** [comment]
Here is first 20 entries in rpairs.tsv, generated by the script:

```
rxn	rpair	met.x	met.y	rptype
R00002	RP00003	C00002	C00008	main
R00002	RP00010	C00002	C00009	leave
R00002	RP05676	C00001	C00009	leave
R00004	RP00190	C00009	C00013	leave
R00004	RP05676	C00001	C00009	leave
R00005	RP05682	C00001	C00011	leave
R00005	RP07361	C00011	C01010	main
R00005	RP07385	C00014	C01010	leave
R00005	RP13530	C00011	C01010	leave
R00005	RP13531	C00014	C01010	leave
R00006	RP00440	C00022	C00900	main
R00006	RP05698	C00011	C00022	leave
R00006	RP12733	C00022	C00900	trans
R00008	RP02868	C00022	C06033	main
R00008	RP13529	C00022	C06033	main
R00009	RP00006	C00007	C00027	main
R00009	RP00130	C00001	C00027	leave
R00010	RP00453	C00031	C01083	main
R00010	RP05679	C00001	C00031	leave
```

The thing is, rpair information have never been available via KEGG API, and moreover recently RPAIR got deprecated to the favor of RCLASS. 

Also, you can try to check out another package called gatom: https://github.com/ctlab/gatom. While it's in a development stage, it works pretty fine and produce much nicer modules.

**Comment by gandrianov** [comment]
Oh. Thank you so much!
You could close this tread.
